<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "work".
 *
 * @property integer $id
 * @property integer $shop_id
 * @property integer $status
 * @property string $date
 * @property string $time_open
 * @property string $time_close
 *
 * @property Shop $shop
 */
class Work extends ActiveRecord
{
    const STATUS_OPEN = 1;
    const STATUS_CLOSE = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'work';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'shop_id', 'status'], 'required'],
            [['shop_id', 'status'], 'integer'],
            [['date', 'time_open', 'time_close'], 'safe'],
            [['shop_id'], 'exist', 'skipOnError' => true, 'targetClass' => Shop::className(), 'targetAttribute' => ['shop_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shop_id' => 'Shop',
            'status' => 'Status',
            'date' => 'Date',
            'time_open' => 'Time Open',
            'time_close' => 'Time Close',
        ];
    }

    /**
     * returns statuses
     * @return mixed
     */
    public static function getStatusList()
    {
        return [ self::STATUS_CLOSE => 'close', self::STATUS_OPEN => 'open'];
    }

    /**
     * gets status name by 'status'
     * @return mixed
     */
    public function getStatusName()
    {
        $list = self::getStatusList();
        return $list[$this->status];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShop()
    {
        return $this->hasOne(Shop::className(), ['id' => 'shop_id']);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if($this->status == self::STATUS_CLOSE) {
            $this->time_open = '00:00';
            $this->time_close = '00:00';
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
